src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use App\Utils\OrderState;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass=OrderRepository::class)
 * @ORM\Table(name="`order`")
 */
class Order
{


    use TimestampableEntity;


    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $total;

    /**
     * @ORM\Column(type="float")
     */
    private $discount;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\OrderItem", mappedBy="order")
     */
    private $orderItems;

    /**
     * @ORM\Column(type="text")
     */
    private $shipping_details;

    /**
     * @ORM\Column(type="string",nullable=true)
     */
    private $shipping_company;


    /**
     * @ORM\Column(type="string",nullable=true)
     */
    private $shipping_tracking_number;


    /**
     * @ORM\Column(type="text",nullable=true)
     */
    private $shipping_label_url;

    /**
     * @ORM\Column(type="boolean",length=1, nullable=true)
     */
    private $has_issue=false;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $box_id=null;


    /**
     * @ORM\Column(type="string")
     */
    private $state=OrderState::ORDER_RECEIVED;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTotal(): ?string
    {
        return $this->total;
    }

    public function setTotal(string $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getDiscount(): ?float
    {
        return $this->discount;
    }

    public function setDiscount(float $discount): self
    {
        $this->discount = $discount;

        return $this;
    }

    public function getOrderItems(): ?Collection
    {
        return $this->orderItems;
    }


    public function getShippingDetails(): ?string
    {
        return $this->shipping_details;
    }

    public function setShippingDetails(string $shipping_details): self
    {
        $this->shipping_details = $shipping_details;

        return $this;
    }

    public function getShippingCompany(): ?string
    {
        return $this->shipping_company;
    }

    public function setShippingCompany(string $shippingCompany): self
    {
        $this->shipping_company = $shippingCompany;

        return $this;
    }

    public function getShippingTrackingNumber(): ?string
    {
        return $this->shipping_tracking_number;
    }

    public function setShippingTrackingNumber(string $shippingTrackingNumber): self
    {
        $this->shipping_tracking_number = $shippingTrackingNumber;

        return $this;
    }

    public function getShippingLabelUrl(): ?string
    {
        return $this->shipping_label_url;
    }

    public function setShippingLabelUrl(string $shippingLabelUrl): self
    {
        $this->shipping_label_url = $shippingLabelUrl;

        return $this;
    }


    public function getHasIssue(): ?bool
    {
        return $this->has_issue;
    }

    public function setHasIssue(bool $hasIssue): self
    {
        $this->has_issue = $hasIssue;
        return $this;
    }

    public function setState(string $state): self
    {
        $this->state = $state;
        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setBoxId(string $boxId): self
    {
        $this->box_id = $boxId;
        return $this;
    }

    public function getBoxId(): ?string
    {
        return $this->box_id;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    /**
     * @param \DateTime $createdAt
     */
    public function setCreatedAt(\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedAt(): \DateTime
    {
        return $this->updatedAt;
    }

    /**
     * @param \DateTime $updatedAt
     */
    public function setUpdatedAt(\DateTime $updatedAt): self
    {
        $this->updatedAt = $updatedAt;
        return $this;
    }









}

src/Entity/OrderStatusLog.php
<?php

namespace App\Entity;

use App\Repository\OrderStatusLogRepository;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass=OrderStatusLogRepository::class)
 */
class OrderStatusLog
{

    use TimestampableEntity;


    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Admin", inversedBy="orderStatusLog")
     */
    private $admin;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Order", inversedBy="orderStatusLog")
     */
    private $order;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $state;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $issue_title;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $issue_value;




    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAdmin(): ?Admin
    {
        return $this->admin;
    }

    public function setAdmin(?Admin $admin): self
    {
        $this->admin = $admin;

        return $this;
    }

    public function getOrder(): ?Order
    {
        return $this->order;
    }

    public function setOrder(?Order $order): self
    {
        $this->order = $order;

        return $this;
    }

    public function getState(): ?string
    {
        return $this->state;
    }

    public function setState(string $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getIssueTitle(): ?string
    {
        return $this->issue_title;
    }

    public function setIssueTitle(?string $issue_title): self
    {
        $this->issue_title = $issue_title;

        return $this;
    }

    public function getIssueValue(): ?string
    {
        return $this->issue_value;
    }

    public function setIssueValue(?string $issue_value): self
    {
        $this->issue_value = $issue_value;

        return $this;
    }
}

templates/picking/order.html.twig
{% extends 'base.html.twig' %}
{% block title %}Picking Departments -Order{% endblock %}
{% block body %}


    <div class="modal" tabindex="-1" role="dialog" id="readyToShip">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true" onclick="$('#readyToShip').modal('hide')">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="shipForm" method="POST" action="/picking/order/make-ready-to-ship">
                        <input type="hidden" name="order_id" value="{{ order.id }}">
                        <input class="form-control" placeholder="Enter Box Id" name="box_id" />
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" onclick="$('#shipForm').submit()" class="btn btn-primary">Ship</button>
                    <button type="button" onclick="$('#readyToShip').modal('hide')" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>





    <div class="container bg-gray">
        <div class="row">
            <h2>Order # {{ order.id }}</h2>
        </div>

        <table class="table table-hover pointer-cursor">

            <tr>
                <td>Order at</td>
                <td>{{ order.createdAt| format_datetime(pattern="yyyy-MM-dd 'at' hh:mm:ss")  }}</td>
            </tr>

            <tr>
                <td>Total Price</td>
                <td>{{  order.total }}</td>
            </tr>

            <tr>
                <td>Total discount</td>
                <td>{{  order.discount }}</td>
            </tr>


            <tr>
                <td>Items</td>
                <td>
                    <ol>
                        {% for item in order.orderItems %}
                            <li> {{ item.item.name }} [{{ item.item.price }}] </li>
                        {% endfor %}
                    </ol>
                </td>
            </tr>

            <tr>
                <td>Order State</td>
                <td>{{  order.state }}</td>
            </tr>

            {% if orderIssueLog != null %}
            <tr>
                <td>Order Issue</td>
                <td style="color: red"><b>[{{  orderIssueLog.issueTitle }}]</b> {{ orderIssueLog.issueValue  }}</td>
            </tr>
            {% endif %}



        </table>


        {% if order.state == "ORDER_RECEIVED" %}
            <div style="text-align: center; margin-top: 10px;">
                <form method="post" action="/picking/order/process">
                    <input type="hidden" name="order_id" value="{{ order.id }}">
                    <button class="btn btn-primary"> Picking Products </button>
                </form>
            </div>
        {% endif %}


        {% if order.state == "ORDER_PROCESSING" %}
            <div style="text-align: center; margin-top: 10px;">
                <button type="button" class="btn btn-primary" data-toggle="modal"
                        data-target="#readyToShip" id="ship">ready to ship</button>
            </div>
        {% endif %}








    </div>



{% endblock %}


{% block scripts %}

    <script>

        $("#ship").on("click",function() {
            $("#readyToShip").modal("show");
        })

        $("#reportItemsIssue").on("click",function() {
            $("#reportIssueModal").modal("show");
        })

        $("#shipOrder").on("click",function() {
            $("#shipOrderModal").modal("show");
        })

    </script>
{% endblock %}

templates/picking/orders.html.twig
{% extends 'base.html.twig' %}
{% block title %} Picking Department - Listings {% endblock %}
{% block body %}

    <div class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Modal title</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>Modal body text goes here.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary">Save changes</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>



    <br>
    <br>


    {% if(orders) %}
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Order ID</th>
                <th>Delivery Address</th>
                <th>state</th>
                <th>Date</th>
                <th>Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for order in orders %}
                <tr>
                    <td>{{ order.id }}</td>
                    <td>{{ order.shippingDetails }}</td>
                    <td>
                        <span class="badge bg-primary">
                            {{ order.state }}
                        </span>
                    </td>
                    <td>{{ order.createdAt| format_datetime(pattern="yyyy-MM-dd 'at' hh:mm:ss") }}</td>
                    <td>
                        <a href="/picking/order/{{ order.id }}/details" class="btn btn-dark">view details</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>no orders</p>
    {% endif %}

    <br>




    <script>


    </script>
{% endblock %}